// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Oo6VXLUsxnlVaChWPzvzFEXnLaT1ZL8',
    appId: '1:316425031253:web:d4b77cfdbf9c0adea08edc',
    messagingSenderId: '316425031253',
    projectId: 'school-manager-2026',
    authDomain: 'school-manager-2026.firebaseapp.com',
    storageBucket: 'school-manager-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Soj1isTC_rjXViSeswTTRfGKLeQIdi4',
    appId: '1:316425031253:android:044406b6f8af659ea08edc',
    messagingSenderId: '316425031253',
    projectId: 'school-manager-2026',
    storageBucket: 'school-manager-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Y8PGMbzSrqLrACp6OS1a7Qa9danD1g0',
    appId: '1:316425031253:ios:ac4a322e5a98787ba08edc',
    messagingSenderId: '316425031253',
    projectId: 'school-manager-2026',
    storageBucket: 'school-manager-2026.firebasestorage.app',
    iosClientId: '316425031253-okcgbe103sgnpoc6qojh4cm0ir6fc6a9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Y8PGMbzSrqLrACp6OS1a7Qa9danD1g0',
    appId: '1:316425031253:ios:ac4a322e5a98787ba08edc',
    messagingSenderId: '316425031253',
    projectId: 'school-manager-2026',
    storageBucket: 'school-manager-2026.firebasestorage.app',
    iosClientId: '316425031253-okcgbe103sgnpoc6qojh4cm0ir6fc6a9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6Oo6VXLUsxnlVaChWPzvzFEXnLaT1ZL8',
    appId: '1:316425031253:web:6af86a9b2fd8a987a08edc',
    messagingSenderId: '316425031253',
    projectId: 'school-manager-2026',
    authDomain: 'school-manager-2026.firebaseapp.com',
    storageBucket: 'school-manager-2026.firebasestorage.app',
  );
}
